# Generated by Django 5.0.3 on 2024-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApprovals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dependants', models.IntegerField()),
                ('applicant_income', models.IntegerField()),
                ('coapplicant_income', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('loan_term', models.IntegerField()),
                ('credit_history', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=15)),
                ('married', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=15)),
                ('graduate', models.CharField(choices=[('graduate', 'graduated'), ('not_graduate', 'not_graduate')], max_length=15)),
                ('self_employed', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=15)),
                ('area', models.CharField(choices=[('rural', 'rural'), ('semiurban', 'semiurban'), ('urban', 'urban')], max_length=15)),
            ],
        ),
    ]
